### ISSUE TITLE
Importing additional rust targets

### ISSUE THREAD

**Issue by tampanoel** [drmikehenry/romt#25] opened 2024-12-09 19:44 UTC
Disconnect environment. Tasked to import additional rust targets (i.e. mips-unknown-linux-musl). On the exporter, **romt toolchain --select stable all-targets | grep musl** lists the targets I need. But when I try to download with **romt toolchain download pack --select stable --target mipsel-unknown-linux-musl**, I get 

Pack: stable
  ident: stable-2024-11-28(1.83.0)
Traceback (most recent call last):
  File "romt-wrapper.py", line 5, in <module>
  File "romt/cli.py", line 214, in main
  File "romt/cli.py", line 199, in run
  File "romt/base.py", line 52, in run
  File "romt/toolchain.py", line 750, in _run
  File "romt/toolchain.py", line 567, in cmd_pack
  File "romt/toolchain.py", line 415, in downloaded_target_packages
KeyError: 'mipsel-unknown-linux-musl'
[1697854] Failed to execute script 'romt-wrapper' due to unhandled exception!

What am I doing wrong?
Thanks in advance!

**Comment by drmikehenry** [comment] 2024-12-10 11:23
Sorry for the unhelpful error message; that should be improved.

Fundamentally, the problem is that `mipsel-unknown-linux-musl` is a Tier 3 target:
<https://doc.rust-lang.org/rustc/platform-support.html#tier-3>

This means that the Rust team doesn't build or test any code (including the Rust standard library) for that target.  You can see which targets are available via the "Rustup Components History" page as well:
<https://rust-lang.github.io/rustup-components-history/>

Down in the "Tier 3" section at the bottom, you can see that `mipsel-unknown-linux-musl` is listed without a hyper link to the build status.  The target is known in the sense that the Rust standard library source code has support for this target, but as the Rust team doesn't build for that target, there are no artifacts to link.  (Even the Tier 3 targets with hyperlinks don't have any substantial components; generally only the Rust documentation is linked for certain Tier 3 targets).

Similarly, Romt knows of your target's existence, but isn't checking that the target is properly installable and providing a good error message to that effect when you try to download.

You can verify that the target is unavailable as follows:

```sh
rustup install 1.83.0
rustup +1.83.0 target add mipsel-unknown-linux-musl
```

This generates the error message:

```text
error: component 'rust-std' for target 'mipsel-unknown-linux-musl' is unavailable for download for channel '1.83.0'
```

It's still possible to cross-compile for your target.  The details are out-of-scope for Romt, but John Hagen's excellent `min-sized-rust` project can demonstrate some of the steps required:
<https://github.com/johnthagen/min-sized-rust>

Building the Rust standard library (which is the Rust component that gets installed via `rustup target add`) requires a Nightly toolchain, along with the `rust-src` component (which contains the source code to the Rust standard library):

```sh
rustup install nightly-2024-12-09
rustup +nightly-2024-12-09 component add rust-src
```

Using `min-sized-rust`, build the `build_std` example as follows:

```sh

git clone https://github.com/johnthagen/min-sized-rust.git
cd min-sized-rust/build_std
cargo +nightly-2024-12-09 build -Z build-std=std,panic_abort --target mipsel-unknown-linux-musl --release
```

This will not completely succeed because cross-compilation for this target requires installation of a cross linker for the target.

**Comment by drmikehenry** [comment] 2024-12-30 22:54
I'm closing this issue on the assumption that there's nothing more to do (other than improve the error message, which is now on the long-term TODO list).

**Closed by drmikehenry** 2024-12-30 22:54 UTC
